server:
  port: 8004

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pipeline_db

backend:
  flink:
    mongo-collection-name: pipelines
    python-command: python3
    python-activation-script:
    python-runner-path: backend/scripts/reference_runner_cli.py
    python-working-directory: .
    cors:
      allowed-origin-patterns:
        - http://localhost:*
        - http://127.0.0.1:*
        - https://localhost:*
        - https://127.0.0.1:*
